/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 // ceci est une addition
package Guis;

import java.util.*;
import java.text.*;

/**
 *
 * @author kiel
 */
public class CapitainerieFrame extends java.awt.Frame {
    
    protected boolean connected;

    /**
     * Creates new form NewFrame
     */
    public CapitainerieFrame() {
        connected = true;
        c = Calendar.getInstance();
        date = c.getTime();
        df = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT);
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAuteurs = new javax.swing.JDialog();
        jLabelJeunemaitre = new javax.swing.JLabel();
        jLabelJeunemaitre1 = new javax.swing.JLabel();
        jDialogAide = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jDialogFormatDate = new javax.swing.JDialog();
        jLabelPays = new javax.swing.JLabel();
        jLabelFormatDate = new javax.swing.JLabel();
        jLabelFormatHeure = new javax.swing.JLabel();
        jComboBoxPays = new javax.swing.JComboBox();
        jComboBoxFormatDate = new javax.swing.JComboBox();
        jComboBoxFormatHeure = new javax.swing.JComboBox();
        jButtonAppliquerFormatDate = new javax.swing.JButton();
        jButtonAnnulerFormatDate = new javax.swing.JButton();
        jDialogListeAmarrages = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeAmarrages = new javax.swing.JTable();
        jLabelEmplacement = new javax.swing.JLabel();
        jButtonChoisirEmplacement = new javax.swing.JButton();
        jButtonAnnulerEmplacement = new javax.swing.JButton();
        jDialogListeBateaux = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBateaux = new javax.swing.JTable();
        jDialogEquipage = new javax.swing.JDialog();
        jDialogChercherBateau = new javax.swing.JDialog();
        jLabelRechercherNomBateau = new javax.swing.JLabel();
        jTextFieldRechercherNomBateau = new javax.swing.JTextField();
        jTextFieldRechercherPortBateau = new javax.swing.JTextField();
        jLabelRechercherBateauEmplacement = new javax.swing.JLabel();
        jLabelRechercherBateauBateau = new javax.swing.JLabel();
        jLabelRechercherBateauPavillon = new javax.swing.JLabel();
        jLabelRechercherBateauPortAttache = new javax.swing.JLabel();
        jLabelRechercherBateauTonnage = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListRechercherBateauEquipage = new javax.swing.JList();
        jLabelRechercherBateauEquipage = new javax.swing.JLabel();
        jButtonDemarrerServeur = new javax.swing.JButton();
        jCheckBoxRequeteEnAttente = new javax.swing.JCheckBox();
        jButtonLire = new javax.swing.JButton();
        jTextFieldLire = new javax.swing.JTextField();
        jLabelAmarragePossible = new javax.swing.JLabel();
        jButtonChoisir = new javax.swing.JButton();
        jTextFieldChoisir = new javax.swing.JTextField();
        jButtonEnvoyerChoix = new javax.swing.JButton();
        jTextFieldEnvoyerChoix = new javax.swing.JTextField();
        jButtonEnvoyerConfirmation = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        capitainerieMenuBar = new java.awt.MenuBar();
        utilisateursMenu = new java.awt.Menu();
        loginMenuItem = new java.awt.MenuItem();
        logoutMenuItem = new java.awt.MenuItem();
        nouveauMenuItem = new java.awt.MenuItem();
        amarragesMenu = new java.awt.Menu();
        plaisanceMenuItem = new java.awt.MenuItem();
        pecheMenuItem = new java.awt.MenuItem();
        bateauxMenu = new java.awt.Menu();
        bateauxListeCompleteMenuItem = new java.awt.MenuItem();
        rechercherBateauMenuItem = new java.awt.MenuItem();
        personnelMenu = new java.awt.Menu();
        equipageBateauMenuItem = new java.awt.MenuItem();
        rechercherMarinMenuItem = new java.awt.MenuItem();
        parametresMenu = new java.awt.Menu();
        formatDateMenuItem = new java.awt.MenuItem();
        fichierLogMenuItem = new java.awt.MenuItem();
        affichagedateCheckBoxMenuItem = new java.awt.CheckboxMenuItem();
        aproposMenu = new java.awt.Menu();
        auteursMenuItem = new java.awt.MenuItem();
        aideMenuItem = new java.awt.MenuItem();

        jDialogAuteurs.setTitle("Auteurs");
        jDialogAuteurs.setMinimumSize(new java.awt.Dimension(318, 67));
        jDialogAuteurs.setModal(true);

        jLabelJeunemaitre.setText("JEUNEMAITRE Antony");

        jLabelJeunemaitre1.setText("JAMEIGNE Lionel");

        javax.swing.GroupLayout jDialogAuteursLayout = new javax.swing.GroupLayout(jDialogAuteurs.getContentPane());
        jDialogAuteurs.getContentPane().setLayout(jDialogAuteursLayout);
        jDialogAuteursLayout.setHorizontalGroup(
            jDialogAuteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAuteursLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelJeunemaitre)
                .addGap(65, 65, 65)
                .addComponent(jLabelJeunemaitre1)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jDialogAuteursLayout.setVerticalGroup(
            jDialogAuteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAuteursLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jDialogAuteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJeunemaitre)
                    .addComponent(jLabelJeunemaitre1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jDialogAide.setTitle("Aide");
        jDialogAide.setMinimumSize(new java.awt.Dimension(409, 358));
        jDialogAide.setModal(true);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Ceci est l'aide de l'appli Inpres Harbour!\n\nLorem ipsum etc\nSinon il parait que google est notre ami...\nEnfin tout ça pour montrer qu'on a bien des scrollers.\n\nDu coup...\nIl nous faut rajouter du texte!\n\nDes phrases à rallonge que diable!\n\nLes chaussettes de l'archiduchesse sont-elles sèches archi sèches?");
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAideLayout = new javax.swing.GroupLayout(jDialogAide.getContentPane());
        jDialogAide.getContentPane().setLayout(jDialogAideLayout);
        jDialogAideLayout.setHorizontalGroup(
            jDialogAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDialogAideLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogAideLayout.setVerticalGroup(
            jDialogAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogFormatDate.setTitle("Format de la date");
        jDialogFormatDate.setMinimumSize(new java.awt.Dimension(295, 210));
        jDialogFormatDate.setModal(true);

        jLabelPays.setText("Pays");

        jLabelFormatDate.setText("Format de la date");

        jLabelFormatHeure.setText("Format de l'heure");

        jComboBoxPays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "France", "Royaume-Uni", "Allemagne", "Italie", "USA" }));

        jComboBoxFormatDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jj/mm/aaaa", "mm/jj/aaaa", "jjjj/mmmm/aaaa", "mmmm/jjjj/aaaa" }));

        jComboBoxFormatHeure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "24h", "12h" }));
        jComboBoxFormatHeure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatHeureActionPerformed(evt);
            }
        });

        jButtonAppliquerFormatDate.setText("Appliquer");
        jButtonAppliquerFormatDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppliquerFormatDateActionPerformed(evt);
            }
        });

        jButtonAnnulerFormatDate.setText("Annuler");
        jButtonAnnulerFormatDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerFormatDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogFormatDateLayout = new javax.swing.GroupLayout(jDialogFormatDate.getContentPane());
        jDialogFormatDate.getContentPane().setLayout(jDialogFormatDateLayout);
        jDialogFormatDateLayout.setHorizontalGroup(
            jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogFormatDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogFormatDateLayout.createSequentialGroup()
                        .addComponent(jLabelFormatHeure)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxFormatHeure, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogFormatDateLayout.createSequentialGroup()
                        .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFormatDate)
                            .addComponent(jLabelPays))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPays, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxFormatDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jDialogFormatDateLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonAppliquerFormatDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAnnulerFormatDate)
                .addGap(50, 50, 50))
        );
        jDialogFormatDateLayout.setVerticalGroup(
            jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogFormatDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPays)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFormatDate)
                    .addComponent(jComboBoxFormatDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFormatHeure)
                    .addComponent(jComboBoxFormatHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jDialogFormatDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAppliquerFormatDate)
                    .addComponent(jButtonAnnulerFormatDate))
                .addContainerGap())
        );

        jDialogListeAmarrages.setTitle("Liste des amarrages");

        jTableListeAmarrages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ponton", "Emplacement", "Bateau", "Port d'attache"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListeAmarrages);

        jLabelEmplacement.setText("Emplacement: ");

        jButtonChoisirEmplacement.setText("Choisir");

        jButtonAnnulerEmplacement.setText("Annuler");

        javax.swing.GroupLayout jDialogListeAmarragesLayout = new javax.swing.GroupLayout(jDialogListeAmarrages.getContentPane());
        jDialogListeAmarrages.getContentPane().setLayout(jDialogListeAmarragesLayout);
        jDialogListeAmarragesLayout.setHorizontalGroup(
            jDialogListeAmarragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeAmarragesLayout.createSequentialGroup()
                .addGroup(jDialogListeAmarragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogListeAmarragesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogListeAmarragesLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jDialogListeAmarragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEmplacement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonChoisirEmplacement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnnulerEmplacement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jDialogListeAmarragesLayout.setVerticalGroup(
            jDialogListeAmarragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeAmarragesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmplacement)
                .addGap(44, 44, 44)
                .addGroup(jDialogListeAmarragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChoisirEmplacement)
                    .addComponent(jButtonAnnulerEmplacement))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jDialogListeBateaux.setTitle("Liste des bateaux");
        jDialogListeBateaux.setName("Liste des bateaux"); // NOI18N

        jTableBateaux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Port d'attache", "Amarrage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableBateaux);

        javax.swing.GroupLayout jDialogListeBateauxLayout = new javax.swing.GroupLayout(jDialogListeBateaux.getContentPane());
        jDialogListeBateaux.getContentPane().setLayout(jDialogListeBateauxLayout);
        jDialogListeBateauxLayout.setHorizontalGroup(
            jDialogListeBateauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeBateauxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogListeBateauxLayout.setVerticalGroup(
            jDialogListeBateauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeBateauxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEquipageLayout = new javax.swing.GroupLayout(jDialogEquipage.getContentPane());
        jDialogEquipage.getContentPane().setLayout(jDialogEquipageLayout);
        jDialogEquipageLayout.setHorizontalGroup(
            jDialogEquipageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogEquipageLayout.setVerticalGroup(
            jDialogEquipageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialogChercherBateau.setTitle("Rechercher un bateau");
        jDialogChercherBateau.setName("jDialogChercherBateau"); // NOI18N

        jLabelRechercherNomBateau.setText("Nom du bateau: ");

        jLabelRechercherBateauEmplacement.setText("Emplacement: ");

        jLabelRechercherBateauBateau.setText("Bateau: ");

        jLabelRechercherBateauPavillon.setText("Pavillon: ");

        jLabelRechercherBateauPortAttache.setText("Port d'attache: ");

        jLabelRechercherBateauTonnage.setText("Tonnage: ");

        jScrollPane4.setViewportView(jListRechercherBateauEquipage);

        jLabelRechercherBateauEquipage.setText("Equipage:");

        javax.swing.GroupLayout jDialogChercherBateauLayout = new javax.swing.GroupLayout(jDialogChercherBateau.getContentPane());
        jDialogChercherBateau.getContentPane().setLayout(jDialogChercherBateauLayout);
        jDialogChercherBateauLayout.setHorizontalGroup(
            jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogChercherBateauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogChercherBateauLayout.createSequentialGroup()
                        .addComponent(jLabelRechercherBateauPortAttache)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldRechercherPortBateau))
                    .addGroup(jDialogChercherBateauLayout.createSequentialGroup()
                        .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRechercherNomBateau)
                            .addComponent(jLabelRechercherBateauEquipage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRechercherNomBateau)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                    .addGroup(jDialogChercherBateauLayout.createSequentialGroup()
                        .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRechercherBateauEmplacement)
                            .addComponent(jLabelRechercherBateauBateau)
                            .addComponent(jLabelRechercherBateauTonnage)
                            .addComponent(jLabelRechercherBateauPavillon))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogChercherBateauLayout.setVerticalGroup(
            jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogChercherBateauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRechercherNomBateau)
                    .addComponent(jTextFieldRechercherNomBateau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRechercherBateauPortAttache)
                    .addComponent(jTextFieldRechercherPortBateau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabelRechercherBateauEmplacement)
                .addGap(18, 18, 18)
                .addComponent(jLabelRechercherBateauBateau)
                .addGap(18, 18, 18)
                .addComponent(jLabelRechercherBateauPavillon)
                .addGap(19, 19, 19)
                .addComponent(jLabelRechercherBateauTonnage)
                .addGap(18, 18, 18)
                .addGroup(jDialogChercherBateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRechercherBateauEquipage)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLocationRelativeTo(null);
        setMinimumSize(new java.awt.Dimension(900, 450));
        setName("FrameCapitainerie"); // NOI18N
        setTitle("Capitainerie d'Inpres-Harbour");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButtonDemarrerServeur.setText("Démarrer le serveur");
        jButtonDemarrerServeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDemarrerServeurActionPerformed(evt);
            }
        });

        jCheckBoxRequeteEnAttente.setText("Requête en attente");

        jButtonLire.setText("Lire");
        jButtonLire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLireActionPerformed(evt);
            }
        });

        jTextFieldLire.setText("??");

        jLabelAmarragePossible.setForeground(new java.awt.Color(102, 102, 102));
        jLabelAmarragePossible.setText("Amarrage possible :");

        jButtonChoisir.setText("Choisir");

        jTextFieldChoisir.setText("??");

        jButtonEnvoyerChoix.setText("Envoyer Choix");
        jButtonEnvoyerChoix.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextFieldEnvoyerChoix.setText("???");

        jButtonEnvoyerConfirmation.setText("Envoyer Confirmation");
        jButtonEnvoyerConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvoyerConfirmationActionPerformed(evt);
            }
        });

        jLabelDate.setText(df.format(date)
        );

        utilisateursMenu.setLabel("Utilisateurs");
        utilisateursMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateursMenuActionPerformed(evt);
            }
        });

        loginMenuItem.setEnabled(false);
        loginMenuItem.setLabel("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        utilisateursMenu.add(loginMenuItem);

        logoutMenuItem.setLabel("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        utilisateursMenu.add(logoutMenuItem);

        nouveauMenuItem.setLabel("Nouveau");
        nouveauMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauMenuItemActionPerformed(evt);
            }
        });
        utilisateursMenu.add(nouveauMenuItem);

        capitainerieMenuBar.add(utilisateursMenu);

        amarragesMenu.setLabel("Amarrages");

        plaisanceMenuItem.setLabel("Plaisance");
        amarragesMenu.add(plaisanceMenuItem);

        pecheMenuItem.setLabel("Pêche");
        amarragesMenu.add(pecheMenuItem);

        capitainerieMenuBar.add(amarragesMenu);

        bateauxMenu.setLabel("Bateaux");

        bateauxListeCompleteMenuItem.setLabel("Liste complète");
        bateauxMenu.add(bateauxListeCompleteMenuItem);

        rechercherBateauMenuItem.setLabel("Rechercher un bateau");
        bateauxMenu.add(rechercherBateauMenuItem);

        capitainerieMenuBar.add(bateauxMenu);

        personnelMenu.setLabel("Personnel");

        equipageBateauMenuItem.setLabel("Equipage d'un bateau");
        personnelMenu.add(equipageBateauMenuItem);

        rechercherMarinMenuItem.setLabel("Rechercher un marin");
        personnelMenu.add(rechercherMarinMenuItem);

        capitainerieMenuBar.add(personnelMenu);

        parametresMenu.setLabel("Paramètres");

        formatDateMenuItem.setLabel("Format date");
        formatDateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatDateMenuItemActionPerformed(evt);
            }
        });
        parametresMenu.add(formatDateMenuItem);

        fichierLogMenuItem.setLabel("Fichier log");
        parametresMenu.add(fichierLogMenuItem);

        affichagedateCheckBoxMenuItem.setLabel("Affichage date-heure courante");
        affichagedateCheckBoxMenuItem.setState(true);
        affichagedateCheckBoxMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                affichagedateCheckBoxMenuItemItemStateChanged(evt);
            }
        });
        parametresMenu.add(affichagedateCheckBoxMenuItem);

        capitainerieMenuBar.add(parametresMenu);

        aproposMenu.setLabel("A Propos");

        auteursMenuItem.setLabel("Auteurs");
        auteursMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auteursMenuItemActionPerformed(evt);
            }
        });
        aproposMenu.add(auteursMenuItem);

        aideMenuItem.setLabel("Aide");
        aideMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aideMenuItemActionPerformed(evt);
            }
        });
        aproposMenu.add(aideMenuItem);

        capitainerieMenuBar.add(aproposMenu);

        setMenuBar(capitainerieMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDemarrerServeur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDate)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxRequeteEnAttente)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonLire)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLire))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAmarragePossible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChoisir)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldChoisir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEnvoyerChoix)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEnvoyerChoix, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEnvoyerConfirmation)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDemarrerServeur)
                    .addComponent(jLabelDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRequeteEnAttente)
                    .addComponent(jButtonLire)
                    .addComponent(jTextFieldLire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmarragePossible)
                    .addComponent(jButtonChoisir)
                    .addComponent(jTextFieldChoisir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnvoyerChoix)
                    .addComponent(jTextFieldEnvoyerChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnvoyerConfirmation))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void utilisateursMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateursMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilisateursMenuActionPerformed

    private void jButtonDemarrerServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDemarrerServeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDemarrerServeurActionPerformed

    private void jButtonLireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLireActionPerformed

    private void jButtonEnvoyerConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvoyerConfirmationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnvoyerConfirmationActionPerformed

    private void auteursMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auteursMenuItemActionPerformed
        jDialogAuteurs.setVisible(true);
    }//GEN-LAST:event_auteursMenuItemActionPerformed

    private void aideMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aideMenuItemActionPerformed
        jDialogAide.setVisible(true);
    }//GEN-LAST:event_aideMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialogAide.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxFormatHeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatHeureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFormatHeureActionPerformed

    private void jButtonAppliquerFormatDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppliquerFormatDateActionPerformed
        jDialogFormatDate.setVisible(false);
    }//GEN-LAST:event_jButtonAppliquerFormatDateActionPerformed

    private void jButtonAnnulerFormatDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerFormatDateActionPerformed
        jDialogFormatDate.setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerFormatDateActionPerformed

    private void formatDateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatDateMenuItemActionPerformed
        jDialogFormatDate.setVisible(true);
    }//GEN-LAST:event_formatDateMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void nouveauMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nouveauMenuItemActionPerformed

    private void affichagedateCheckBoxMenuItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_affichagedateCheckBoxMenuItemItemStateChanged
        jLabelDate.setVisible(affichagedateCheckBoxMenuItem.getState());
    }//GEN-LAST:event_affichagedateCheckBoxMenuItemItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapitainerieFrame().setVisible(true);
            }
        });
    }


    private Calendar c;
    private Date date;
    private DateFormat df;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.CheckboxMenuItem affichagedateCheckBoxMenuItem;
    private java.awt.MenuItem aideMenuItem;
    private java.awt.Menu amarragesMenu;
    private java.awt.Menu aproposMenu;
    private java.awt.MenuItem auteursMenuItem;
    private java.awt.MenuItem bateauxListeCompleteMenuItem;
    private java.awt.Menu bateauxMenu;
    private java.awt.MenuBar capitainerieMenuBar;
    private java.awt.MenuItem equipageBateauMenuItem;
    private java.awt.MenuItem fichierLogMenuItem;
    private java.awt.MenuItem formatDateMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnnulerEmplacement;
    private javax.swing.JButton jButtonAnnulerFormatDate;
    private javax.swing.JButton jButtonAppliquerFormatDate;
    private javax.swing.JButton jButtonChoisir;
    private javax.swing.JButton jButtonChoisirEmplacement;
    private javax.swing.JButton jButtonDemarrerServeur;
    private javax.swing.JButton jButtonEnvoyerChoix;
    private javax.swing.JButton jButtonEnvoyerConfirmation;
    private javax.swing.JButton jButtonLire;
    private javax.swing.JCheckBox jCheckBoxRequeteEnAttente;
    private javax.swing.JComboBox jComboBoxFormatDate;
    private javax.swing.JComboBox jComboBoxFormatHeure;
    private javax.swing.JComboBox jComboBoxPays;
    private javax.swing.JDialog jDialogAide;
    private javax.swing.JDialog jDialogAuteurs;
    private javax.swing.JDialog jDialogChercherBateau;
    private javax.swing.JDialog jDialogEquipage;
    private javax.swing.JDialog jDialogFormatDate;
    private javax.swing.JDialog jDialogListeAmarrages;
    private javax.swing.JDialog jDialogListeBateaux;
    private javax.swing.JLabel jLabelAmarragePossible;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEmplacement;
    private javax.swing.JLabel jLabelFormatDate;
    private javax.swing.JLabel jLabelFormatHeure;
    private javax.swing.JLabel jLabelJeunemaitre;
    private javax.swing.JLabel jLabelJeunemaitre1;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JLabel jLabelRechercherBateauBateau;
    private javax.swing.JLabel jLabelRechercherBateauEmplacement;
    private javax.swing.JLabel jLabelRechercherBateauEquipage;
    private javax.swing.JLabel jLabelRechercherBateauPavillon;
    private javax.swing.JLabel jLabelRechercherBateauPortAttache;
    private javax.swing.JLabel jLabelRechercherBateauTonnage;
    private javax.swing.JLabel jLabelRechercherNomBateau;
    private javax.swing.JList jListRechercherBateauEquipage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableBateaux;
    private javax.swing.JTable jTableListeAmarrages;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldChoisir;
    private javax.swing.JTextField jTextFieldEnvoyerChoix;
    private javax.swing.JTextField jTextFieldLire;
    private javax.swing.JTextField jTextFieldRechercherNomBateau;
    private javax.swing.JTextField jTextFieldRechercherPortBateau;
    private java.awt.MenuItem loginMenuItem;
    private java.awt.MenuItem logoutMenuItem;
    private java.awt.MenuItem nouveauMenuItem;
    private java.awt.Menu parametresMenu;
    private java.awt.MenuItem pecheMenuItem;
    private java.awt.Menu personnelMenu;
    private java.awt.MenuItem plaisanceMenuItem;
    private java.awt.MenuItem rechercherBateauMenuItem;
    private java.awt.MenuItem rechercherMarinMenuItem;
    private java.awt.Menu utilisateursMenu;
    // End of variables declaration//GEN-END:variables
}
